version: '3.4'

services:
  app:
    image: golang:1.15-alpine3.12
    working_dir: /app
    volumes:
      - ./:/app:cached
    depends_on:
      - db

  db:
    image: mysql:5.7.25
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - "5306:3306"
